-- Create Categories Table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  type text not null check (type in ('work', 'life')),
  color text,
  "order" int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Priorities Table
create table if not exists public.priorities (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  color text,
  "order" int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.priorities enable row level security;
alter table public.categories enable row level security;

-- RLS Policies for Priorities
create policy "Users can view their own priorities" on public.priorities for select using (auth.uid() = user_id);
create policy "Users can insert their own priorities" on public.priorities for insert with check (auth.uid() = user_id);
create policy "Users can update their own priorities" on public.priorities for update using (auth.uid() = user_id);
create policy "Users can delete their own priorities" on public.priorities for delete using (auth.uid() = user_id);

-- RLS Policies for Categories
create policy "Users can view their own categories" on public.categories for select using (auth.uid() = user_id);
create policy "Users can insert their own categories" on public.categories for insert with check (auth.uid() = user_id);
create policy "Users can update their own categories" on public.categories for update using (auth.uid() = user_id);
create policy "Users can delete their own categories" on public.categories for delete using (auth.uid() = user_id);
