-- Create "Category Types" table (if it doesn't exist)
create table if not exists public.category_types (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  "order" int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, name)
);

-- Enable Security (idempotent)
alter table public.category_types enable row level security;

-- Drop existing policies to avoid conflicts
drop policy if exists "Users can view their own category types" on public.category_types;
drop policy if exists "Users can insert their own category types" on public.category_types;
drop policy if exists "Users can update their own category types" on public.category_types;
drop policy if exists "Users can delete their own category types" on public.category_types;

-- Re-create policies
create policy "Users can view their own category types" on public.category_types for select using (auth.uid() = user_id);
create policy "Users can insert their own category types" on public.category_types for insert with check (auth.uid() = user_id);
create policy "Users can update their own category types" on public.category_types for update using (auth.uid() = user_id);
create policy "Users can delete their own category types" on public.category_types for delete using (auth.uid() = user_id);

-- Import your existing types (One time only)
insert into public.category_types (user_id, name, "order")
select distinct user_id, type, 0
from public.categories
where type is not null
on conflict (user_id, name) do nothing;
